import type { Metadata } from "next";
import { Radio_Canada } from "next/font/google";
import "./globals.css";

const font = Radio_Canada({ subsets: ["latin"], weight: ['400'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} h-calc[100vh] w-calc[100vw] font-bold`}>
        {children}
      </body>
    </html>
  );
}
